// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-treatments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4";

// src/lib/mcp/data.ts
var treatments = [
  {
    slug: "prp",
    name: "PRP (Plasma Rico en Plaquetas) \u2013 Facial y Capilar",
    description: "Medicina regenerativa con plasma rico en plaquetas del propio paciente. Estimula la regeneraci\xF3n celular, mejora la calidad de la piel y trata la ca\xEDda del cabello.",
    category: "estetica"
  },
  {
    slug: "mesoterapia",
    name: "Mesoterapia Facial y Capilar",
    description: "Microinyecciones de principios activos espec\xEDficos. Revitaliza la piel del rostro, mejora la hidrataci\xF3n y estimula el crecimiento capilar.",
    category: "estetica"
  },
  {
    slug: "bioestimulacion",
    name: "Bioestimulaci\xF3n Facial",
    description: "Tratamiento no invasivo que estimula la producci\xF3n de col\xE1geno y elastina, mejorando textura, firmeza y luminosidad de la piel.",
    category: "estetica"
  },
  {
    slug: "toxina-botulinica",
    name: "Toxina Botul\xEDnica",
    description: "Aplicaci\xF3n profesional para suavizar arrugas de expresi\xF3n en frente, entrecejo y patas de gallo, con resultados naturales.",
    category: "estetica"
  },
  {
    slug: "rellenos-dermicos",
    name: "Rellenos D\xE9rmicos con \xC1cido Hialur\xF3nico",
    description: "Correcci\xF3n de surcos nasogenianos y aumento de volumen en labios y p\xF3mulos con \xE1cido hialur\xF3nico de alta calidad.",
    category: "estetica"
  },
  {
    slug: "peelings-quimicos",
    name: "Peelings Qu\xEDmicos",
    description: "Exfoliaci\xF3n controlada con \xE1cidos espec\xEDficos. Mejora textura, reduce manchas, cicatrices de acn\xE9 y signos de envejecimiento.",
    category: "estetica"
  },
  {
    slug: "mesolifting",
    name: "Mesolifting",
    description: "Vitaminas, amino\xE1cidos y antioxidantes en microinyecciones para un efecto lifting natural sin cirug\xEDa.",
    category: "estetica"
  },
  {
    slug: "criocirugia",
    name: "Criocirug\xEDa",
    description: "Fr\xEDo terap\xE9utico para eliminar lesiones cut\xE1neas benignas y malignas: verrugas, queratosis act\xEDnicas y otros tumores de piel.",
    category: "clinica"
  },
  {
    slug: "dermatoscopia",
    name: "Dermatoscop\xEDa",
    description: "Examen no invasivo de lunares y lesiones cut\xE1neas para detecci\xF3n temprana de melanoma y otros tipos de c\xE1ncer de piel.",
    category: "clinica"
  }
];
var offices = [
  {
    slug: "vicente-lopez",
    name: "Consultorio Vicente L\xF3pez",
    address: "Av. Maip\xFA 1651, Piso 2",
    city: "Vicente L\xF3pez",
    province: "Buenos Aires",
    postalCode: "1638",
    phone: "+54 11 3368-1890",
    whatsapp: "https://wa.me/5491133681890",
    hours: ["Lunes: 15 a 19 hs", "Martes: 15 a 19 hs"]
  },
  {
    slug: "capilla-del-senor",
    name: "Consultorio Capilla del Se\xF1or",
    address: "Bartolom\xE9 Mitre 480",
    city: "Capilla del Se\xF1or",
    province: "Buenos Aires",
    postalCode: "2812",
    phone: "+54 11 7654-6995",
    whatsapp: "https://wa.me/5491176546995",
    hours: ["Mi\xE9rcoles: 9 a 13 hs"]
  }
];
var doctor = {
  name: "Dra. Daniela Bravo",
  specialty: "Dermatolog\xEDa cl\xEDnica y est\xE9tica",
  education: "M\xE9dica egresada de la Universidad de Buenos Aires (UBA), especialista en Dermatolog\xEDa con formaci\xF3n en el Hospital Dr. Houssay de Vicente L\xF3pez.",
  memberships: ["Sociedad Argentina de Dermatolog\xEDa"],
  summary: "Dedicada al cuidado integral de la piel, combinando ciencia, experiencia y atenci\xF3n cercana. Ofrece tratamientos dermatol\xF3gicos y est\xE9ticos personalizados priorizando la seguridad y los resultados naturales.",
  website: "https://dradanielabravo.com",
  areasServed: ["Vicente L\xF3pez", "Capilla del Se\xF1or", "Buenos Aires"]
};

// src/lib/mcp/tools/list-treatments.ts
var list_treatments_default = defineTool({
  name: "list_treatments",
  title: "Listar tratamientos",
  description: "Lista los tratamientos dermatol\xF3gicos y est\xE9ticos ofrecidos por la Dra. Daniela Bravo, con su descripci\xF3n.",
  inputSchema: {
    category: z.enum(["estetica", "clinica"]).optional().describe("Filtrar por tipo: 'estetica' o 'clinica' (dermatolog\xEDa cl\xEDnica)."),
    query: z.string().trim().min(1).optional().describe("Texto libre para buscar por nombre o descripci\xF3n del tratamiento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query }) => {
    const needle = query?.toLowerCase();
    const results = treatments.filter((t) => {
      if (category && t.category !== category) return false;
      if (!needle) return true;
      return t.name.toLowerCase().includes(needle) || t.description.toLowerCase().includes(needle) || t.slug.includes(needle);
    });
    const text = results.length ? results.map((t) => `${t.name} (${t.category}): ${t.description}`).join("\n\n") : "No se encontraron tratamientos con ese criterio.";
    return { content: [{ type: "text", text }], structuredContent: { treatments: results } };
  }
});

// src/lib/mcp/tools/list-offices.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4";
var list_offices_default = defineTool2({
  name: "list_offices",
  title: "Consultorios y horarios",
  description: "Devuelve los consultorios de la Dra. Daniela Bravo con direcci\xF3n, horarios de atenci\xF3n, tel\xE9fono y enlace de WhatsApp para pedir turno.",
  inputSchema: {
    city: z2.string().trim().min(1).optional().describe("Filtrar por ciudad, por ejemplo 'Vicente L\xF3pez' o 'Capilla del Se\xF1or'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ city }) => {
    const needle = city?.toLowerCase();
    const results = offices.filter(
      (o) => !needle || o.city.toLowerCase().includes(needle) || o.slug.includes(needle.replace(/\s+/g, "-"))
    );
    const text = results.length ? results.map(
      (o) => `${o.name}
Direcci\xF3n: ${o.address}, ${o.city}, ${o.province} (CP ${o.postalCode})
Horarios: ${o.hours.join(" | ")}
Tel\xE9fono: ${o.phone}
WhatsApp: ${o.whatsapp}`
    ).join("\n\n") : "No se encontr\xF3 un consultorio para esa ciudad.";
    return { content: [{ type: "text", text }], structuredContent: { offices: results } };
  }
});

// src/lib/mcp/tools/get-practice-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_practice_info_default = defineTool3({
  name: "get_practice_info",
  title: "Informaci\xF3n de la pr\xE1ctica",
  description: "Resumen p\xFAblico de la Dra. Daniela Bravo: especialidad, formaci\xF3n, zonas de atenci\xF3n, cantidad de tratamientos y consultorios, y c\xF3mo solicitar un turno.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = [
      `${doctor.name} \u2014 ${doctor.specialty}`,
      doctor.education,
      `Miembro de: ${doctor.memberships.join(", ")}`,
      doctor.summary,
      `Zonas de atenci\xF3n: ${doctor.areasServed.join(", ")}`,
      `Consultorios: ${offices.map((o) => `${o.city} (${o.address})`).join("; ")}`,
      `Tratamientos disponibles: ${treatments.length}. Us\xE1 list_treatments para el detalle.`,
      `Turnos: por WhatsApp \u2014 ${offices.map((o) => `${o.city}: ${o.whatsapp}`).join(" | ")}`,
      `Sitio web: ${doctor.website}`
    ].join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { doctor, offices, treatmentCount: treatments.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bravo-dermatologia-digital",
  title: "bravo-dermatologia-digital",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas del sitio de la Dra. Daniela Bravo, dermat\xF3loga en Vicente L\xF3pez. Us\xE1 get_practice_info para un resumen general, list_treatments para tratamientos dermatol\xF3gicos y est\xE9ticos, y list_offices para direcciones, horarios y enlaces de WhatsApp para pedir turno. No hay datos de pacientes.",
  tools: [get_practice_info_default, list_treatments_default, list_offices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
